[package]
name = "filepick"
version = "0.1.1"
edition = "2021"
description = "随机从一堆文件中抽取指定数量的测试文件。"
license = "MIT"
repository = "https://github.com/binghuis/filepick"

[dependencies]
inquire = "0.7.5"
indicatif = "0.17.8"
